"""Reproducible descriptive statistics and portable HTML reports from raw samples."""

import csv
import hashlib
import json
import math
import os
from collections import defaultdict
from html import escape
from itertools import pairwise
from pathlib import Path

import numpy as np

from .campaign import (
    NOT_RECORDED,
    describe_moment,
    legacy_hardware,
    local_now,
    missing_jobs,
    read_campaign,
)
from .provenance import capture_provenance
from .render_contract import geometry_errors
from .report_layout import compact_report_html, diagnostic_anchor, report_anchor
from .series import run_series, series_svg

TIMING_STAGES = {
    "update": "Synchronous adapter work",
    "conversion": "Conversion (may overlap synchronous work)",
    "draw": "Observed draw work (adapter-specific)",
    "update_complete": "Adapter completion elapsed (includes waiting)",
    "image_upload_wait": "Image allocation wait elapsed",
}

DIAGNOSTIC_KINDS = {
    "replay": (
        "Replay diagnostic",
        "Replay cycles a bounded CPU-resident dataset generated by the same source. It removes "
        "live delivery from the measured path but retains conversion and plotting. Replay runs "
        "are never pooled with streaming repetitions and do not erase source limitations.",
    ),
    "stability": (
        "Stability diagnostic",
        "Longer single runs of one workload. Inspect one-second submitted rates, pauses and RSS "
        "over the whole measured interval. A single check is a spot check, not proof of "
        "leak-free operation, and it does not satisfy the three-repetition sustained rule.",
    ),
    "source_probe": (
        "Source delivery probe",
        "Receiver-only runs with one common Python decode-and-ACK client and no plotting. "
        "They characterize the delivery path for these workloads and are not frontend runs.",
    ),
    "replacement": (
        "Replacement attempts after a harness fix",
        "Attempts that failed in the main campaign for a harness reason and were re-executed "
        "in a fresh directory after the fix. They carry their own source/build identity, are "
        "listed separately, and never replace or pool with the original failed attempts, which "
        "remain visible in the main comparison above.",
    ),
    "extension": (
        "Extension runs merged into the main comparison",
        "Runs of an additional frontend variant recorded later in a separate directory. Runs "
        "whose scenario, configuration, mode, backend and durations match the main suite are "
        "merged into the comparison charts and tables above under their own frontend name, "
        "acquisition dates and provenance; mismatching runs are listed here and excluded.",
    ),
}


def deadline_counter_increase(samples):
    """Observed counter increase; unobserved interval boundaries remain unknown."""
    values = [sample.get("deadline_misses_total") for sample in samples]
    if len(values) < 2 or any(type(value) is not int or value < 0 for value in values):
        return None
    if any(after < before for before, after in pairwise(values)):
        return None
    return values[-1] - values[0]


def single_client_span(samples):
    """Leading source samples with exactly one client; trailing samples after that client
    disconnected are excluded. Any other client count makes the span ambiguous (None).
    """
    span = []
    for index, sample in enumerate(samples):
        clients = sample.get("clients")
        if clients == 1:
            span.append(sample)
            continue
        if span and clients == 0 and all(s.get("clients") == 0 for s in samples[index:]):
            break
        return None
    return span


def delivery_ack_rate(samples):
    """Decoded-and-ACKed delivery rate over the leading single-client counter span."""
    samples = single_client_span(samples)
    if not samples or len(samples) < 2:
        return None
    counters = [sample.get("acknowledgements_total") for sample in samples]
    if any(type(value) is not int or value < 0 for value in counters):
        return None
    if any(after < before for before, after in pairwise(counters)):
        return None
    elapsed = (samples[-1]["time_ms"] - samples[0]["time_ms"]) / 1000
    return (counters[-1] - counters[0]) / elapsed if elapsed > 0 else None


def display_context(metadata):
    context = {
        key: metadata[key]
        for key in (
            "pixel_ratio",
            "viewport_size",
            "viewport",
            "plot_viewports",
            "plot_viewports_all",
            "render_contract",
            "waveform_antialias",
            "monitor_size_logical",
            "window_position_logical",
        )
        if metadata.get(key) is not None
    }
    if metadata.get("display"):
        context["display"] = {
            key: value for key, value in metadata["display"].items() if key != "recorded_at_ms"
        }
    if metadata.get("browser_context"):
        browser = metadata["browser_context"]
        context["browser_startup_screen"] = browser.get("screen")
    return context


def read_jsonl(path):
    if not path.exists():
        return []
    rows = []
    for number, line in enumerate(path.read_text().splitlines(), 1):
        if not line.strip():
            continue
        try:
            rows.append(json.loads(line))
        except json.JSONDecodeError as exc:
            raise ValueError(f"corrupt measurement file {path}:{number}") from exc
    return rows


def percentile(values, q):
    return float(np.percentile(values, q)) if values else None


def collect_samples(folder, manifest):
    """Deduplicated samples for this run, sorted by client time, plus merged metadata."""
    batches = [
        batch
        for batch in read_jsonl(folder / "measurements.jsonl")
        if batch.get("run_id") == manifest["run_id"]
        and batch.get("frontend") == manifest["frontend"]
    ]
    samples, metadata, observed_configs, seen, duplicates = [], {}, [], set(), 0
    for batch in batches:
        metadata.update(batch.get("metadata", {}))
        if batch.get("metadata", {}).get("config"):
            observed_configs.append(batch["metadata"]["config"])
        for sample in batch["samples"]:
            key = sample["generation"], sample["seq"]
            if key in seen:
                duplicates += 1
                continue
            seen.add(key)
            samples.append(sample)
    samples.sort(key=lambda row: row["client_time_ms"])
    return batches, samples, metadata, observed_configs, duplicates


def summarize_run(folder):
    manifest = json.loads((folder / "run.json").read_text())
    batches, samples, metadata, observed_configs, duplicates = collect_samples(folder, manifest)
    row = dict(
        run_id=manifest["run_id"],
        scenario=manifest["scenario"],
        frontend=manifest["frontend"],
        backend=manifest.get("backend", "python"),
        mode=manifest["mode"],
        repetition=manifest["repetition"],
        target_hz=manifest["config"]["hz"],
        status=manifest["status"],
        samples=0,
        submitted_hz=None,
        update_p50_ms=None,
        update_p95_ms=None,
        update_p99_ms=None,
        receive_age_p95_ms=None,
        gap_percent=None,
        cpu_mean_percent=None,
        rss_peak_mib=None,
        source_hz=None,
        source_generation_p95_ms=None,
        source_mailbox_drops=None,
        source_deadline_misses=None,
        source_shortfall_percent=None,
        delivery_drop_percent=None,
        delivery_ack_hz=None,
        provenance=manifest.get("provenance"),
        observed_display_contexts=[],
        duplicate_samples=duplicates,
        measurement_seconds=manifest["measurement_seconds"],
        warmup_seconds=manifest.get("warmup_seconds"),
        metadata=metadata,
        config=manifest["config"],
        error=manifest.get("error"),
        path=folder.name,
    )
    for stage in TIMING_STAGES:
        row[f"{stage}_samples"] = 0
        row[f"{stage}_coverage_percent"] = None
        for q in (50, 95, 99):
            row[f"{stage}_p{q}_ms"] = None
    if not samples:
        row["status"] = "no-data" if row["status"] == "ok" else row["status"]
        return row
    start = samples[0]["client_time_ms"] + manifest["warmup_seconds"] * 1000
    end = start + manifest["measurement_seconds"] * 1000
    measured = [sample for sample in samples if start <= sample["client_time_ms"] < end]
    row["samples"] = len(measured)
    contexts = {}
    for batch in batches:
        if any(start <= sample["client_time_ms"] < end for sample in batch["samples"]):
            context = display_context(batch.get("metadata", {}))
            if context:
                contexts[json.dumps(context, sort_keys=True)] = context
    row["observed_display_contexts"] = list(contexts.values())
    if not measured:
        row["status"] = "no-measured-data"
        return row
    if row["status"] == "ok":
        expected_generation = manifest["config"].get("generation", 0)
        changed = any(sample["generation"] != expected_generation for sample in samples)
        changed |= any(
            any(
                config.get(key) != value
                for key, value in manifest["config"].items()
                if key != "generation"
            )
            for config in observed_configs
        )
        actual_backend = manifest.get("source_health", {}).get("backend", "python")
        source_health = manifest.get("source_health", {})
        if actual_backend != row["backend"]:
            row["status"] = "backend-mismatch"
        elif source_health.get("status", "ok") != "ok" or source_health.get("error"):
            row["status"] = "source-error"
            row["error"] = source_health.get("error") or "source reported unhealthy status"
        elif changed:
            row["status"] = "configuration-changed"
        elif metadata.get("receiver_connection_epoch", 1) > 1:
            row["status"] = "receiver-reconnected"
        elif len(contexts) > 1:
            row["status"] = "display-changed"
        elif any(
            metadata.get(key, 0)
            for key in ("telemetry_lost", "dropped_metric_samples", "unconfirmed_samples")
        ):
            row["status"] = "incomplete-telemetry"
        elif (
            metadata.get("termination_reason", metadata.get("stop_reason", "duration"))
            != "duration"
        ):
            row["status"] = "interrupted"
    render_errors = []
    for batch in batches:
        if any(start <= sample["client_time_ms"] < end for sample in batch["samples"]):
            render_errors.extend(geometry_errors(batch.get("metadata", {}), manifest["config"]))
    if render_errors and row["status"] in ("ok", "render-contract-mismatch"):
        row["status"] = "render-contract-mismatch"
        row["error"] = "; ".join(dict.fromkeys(render_errors))
    duration = manifest["measurement_seconds"]
    row["submitted_hz"] = len(measured) / duration
    for stage in TIMING_STAGES:
        values = [sample.get(f"{stage}_ms") for sample in measured]
        values = [
            value
            for value in values
            if type(value) in (int, float) and math.isfinite(value) and value >= 0
        ]
        row[f"{stage}_samples"] = len(values)
        row[f"{stage}_coverage_percent"] = 100 * len(values) / len(measured)
        for q in (50, 95, 99):
            row[f"{stage}_p{q}_ms"] = percentile(values, q)
    ages = [
        sample["receive_age_ms"] for sample in measured if sample.get("receive_age_ms") is not None
    ]
    row["receive_age_p95_ms"] = percentile(ages, 95)
    gaps, span = 0, 0
    generations = defaultdict(list)
    for sample in measured:
        generations[sample["generation"]].append(sample["seq"])
    for seqs in generations.values():
        current_span = max(seqs) - min(seqs) + 1
        span += current_span
        gaps += current_span - len(set(seqs))
    row["gap_percent"] = 100 * gaps / span if span else None
    resources = [
        sample
        for sample in read_jsonl(folder / "resources.jsonl")
        if start <= sample["time_ms"] < end
    ]
    if resources:
        row["cpu_mean_percent"] = float(np.mean([sample["cpu_percent"] for sample in resources]))
        row["rss_peak_mib"] = max(sample["rss_bytes"] for sample in resources) / 1024**2
    source = [
        sample for sample in read_jsonl(folder / "source.jsonl") if start <= sample["time_ms"] < end
    ]
    if source:
        row["source_hz"] = len(source) / duration
        row["source_generation_p95_ms"] = percentile(
            [sample["generation_ms"] for sample in source if "generation_ms" in sample], 95
        )
        row["source_mailbox_drops"] = sum(sample.get("mailbox_drops", 0) for sample in source)
        row["source_deadline_misses"] = deadline_counter_increase(source)
        row["delivery_ack_hz"] = delivery_ack_rate(source)
        # How far the producer fell below target (source limiting) and how many of the
        # frames it did produce were replaced awaiting ACK (frontend/delivery limiting).
        if row["mode"] == "stream" and row["target_hz"]:
            row["source_shortfall_percent"] = max(
                0.0, 100 * (row["target_hz"] - row["source_hz"]) / row["target_hz"]
            )
        row["delivery_drop_percent"] = 100 * row["source_mailbox_drops"] / len(source)
    # A short startup smoke is deliberately not evidence of a sustained production rate.
    row["sustained_candidate"] = (
        row["status"] == "ok"
        and duration >= 30
        and row["submitted_hz"] >= row["target_hz"] * 0.98
        and row["gap_percent"] <= 1
    )
    row["source_limited"] = (
        row["mode"] == "stream"
        and row["source_hz"] is not None
        and row["source_hz"] < row["target_hz"] * 0.98
    )
    row["sustained_candidate"] &= not row["source_limited"]
    return row


def run_time_series(folder):
    """Per-second submissions and RSS inside the same measured window as summarize_run."""
    manifest = json.loads((folder / "run.json").read_text())
    _, samples, _, _, _ = collect_samples(folder, manifest)
    if not samples:
        return None
    start = samples[0]["client_time_ms"] + manifest["warmup_seconds"] * 1000
    return run_series(
        samples,
        read_jsonl(folder / "resources.jsonl"),
        start_ms=start,
        measurement_seconds=manifest["measurement_seconds"],
        warmup_seconds=manifest["warmup_seconds"],
        target_hz=manifest["config"]["hz"],
    )


def aggregate(rows):
    groups = defaultdict(list)
    for row in rows:
        provenance = row.get("provenance") or {}
        execution_context = dict(
            source_identity=provenance.get("source_sha256") or provenance.get("git"),
            artifact_files={
                key: value.get("files") for key, value in provenance.get("artifacts", {}).items()
            },
            declared_display=provenance.get("display_context"),
            observed_display=display_context(row.get("metadata", {})),
            runtime={
                key: value
                for key, value in row.get("metadata", {}).items()
                if key
                in (
                    "versions",
                    "renderer",
                    "image_renderer",
                    "image_conversion_strategy",
                    "image_conversion_kernel",
                    "shape_renderer_override",
                    "qt_platform_plugin",
                    "renderer_environment",
                    "headless",
                    "browser_version",
                    "browser_selection",
                    "browser_executable",
                    "browser_executable_sha256",
                    "browser_launch_arguments",
                    "browser_network_instrumentation",
                    "playwright_version",
                    "display_protocol_requested",
                    "display_session",
                    "user_agent",
                    "iced_version",
                    "build_profile",
                    "presentation_policy",
                )
                or key.startswith(("gpu_", "opengl_", "graphics_"))
            },
        )
        context_id = hashlib.sha256(
            json.dumps(execution_context, sort_keys=True).encode()
        ).hexdigest()[:12]
        groups[
            row["scenario"], row["mode"], row["frontend"], row.get("backend", "python"), context_id
        ].append(row)
    results = []
    for (scenario, mode, frontend, backend, context_id), runs in sorted(groups.items()):
        valid = [row for row in runs if row["status"] == "ok" and row["submitted_hz"] is not None]
        rates = [row["submitted_hz"] for row in valid]
        results.append(
            dict(
                scenario=scenario,
                mode=mode,
                frontend=frontend,
                backend=backend,
                context_id=context_id,
                attempted=len(runs),
                valid=len(valid),
                target_hz=runs[0]["target_hz"],
                median_hz=percentile(rates, 50),
                min_hz=min(rates) if rates else None,
                max_hz=max(rates) if rates else None,
                source_limited=any(row.get("source_limited") for row in valid),
                repeated_sustained_candidate=len(valid) == len(runs)
                and len(valid) >= 3
                and all(row.get("sustained_candidate") for row in valid),
            )
        )
    return results


def fmt(value, digits=2):
    return "—" if value is None else f"{value:,.{digits}f}"


def text(value):
    """Escaped display text; None and empty values become an explicit 'Not recorded'."""
    if value is None or value == "" or value == []:
        return NOT_RECORDED
    if isinstance(value, (list, dict)):
        return escape(json.dumps(value, sort_keys=True))
    return escape(str(value))


def area_label(dimensions):
    if not isinstance(dimensions, (list, tuple)) or len(dimensions) != 2:
        return "—"
    if any(type(n) not in (int, float) or not math.isfinite(n) or n < 0 for n in dimensions):
        return "—"
    width, height = dimensions
    return f"{width:,.0f} × {height:,.0f} px ({width * height / 1e6:.2f} MP)"


def plot_count(config, field):
    """Plot or curve count of a workload; legacy records without the field mean one."""
    value = config.get(field, 1) if isinstance(config, dict) else 1
    return value if isinstance(value, int) and not isinstance(value, bool) and value > 0 else 1


def plural(count, noun):
    """Grammatically pluralised count: "1 plot", "3 curves"."""
    return f"{count} {noun}{'' if count == 1 else 's'}"


def workload_label(config):
    if not isinstance(config, dict):
        return NOT_RECORDED
    parts = [str(config.get("view", "?"))]
    if config.get("view") in ("waveform", "both"):
        points = config.get("points")
        label = f"{points:,} points" if isinstance(points, int) else "? points"
        if config.get("waveform_mode") == "append":
            label += f" append +{config.get('append_count', '?'):,}"
        else:
            label += " replace"
        plots, curves = plot_count(config, "waveform_plots"), plot_count(config, "curves")
        if plots > 1 or curves > 1:
            label += f" · {plural(plots, 'plot')} × {plural(curves, 'curve')}"
        parts.append(label)
    if config.get("view") in ("image", "both"):
        label = f"{config.get('width', '?')} × {config.get('height', '?')} {config.get('image_mode', '?')}"
        if plot_count(config, "image_plots") > 1:
            label += f" · {plural(plot_count(config, 'image_plots'), 'plot')}"
        parts.append(label)
    parts.append(
        f"{config.get('hz', '?'):g} Hz" if isinstance(config.get("hz"), (int, float)) else "? Hz"
    )
    return " · ".join(parts)


def throughput_svg(groups):
    width, left, right, step = 980, 225, 175, 44
    height = 60 + step * len(groups)
    max_hz = (
        max([group["target_hz"] for group in groups] + [group["max_hz"] or 0 for group in groups])
        * 1.05
    )
    scale = (width - left - right) / max(1, max_hz)
    elements = [
        f'<svg viewBox="0 0 {width} {height}" role="img" aria-label="Submitted update rate by frontend">'
    ]
    for index, group in enumerate(groups):
        y = index * step + 25
        label = group["frontend"]
        if sum(other["frontend"] == label for other in groups) > 1:
            label += f' · {group["context_id"][:6]}'
        elements.append(
            f'<text x="0" y="{y + 17}" fill="#d1deed" font-size="15">{escape(label)}</text>'
        )
        if group["median_hz"] is not None:
            bar = group["median_hz"] * scale
            elements.append(
                f'<rect x="{left}" y="{y}" width="{bar:.2f}" height="25" rx="3" fill="#63d7b9"/>'
            )
            low, high = left + group["min_hz"] * scale, left + group["max_hz"] * scale
            elements.append(
                f'<path d="M{low} {y + 12.5} H{high}" stroke="#ffffff" stroke-width="2"/>'
            )
        target = left + group["target_hz"] * scale
        elements.append(f'<path d="M{target} {y - 3} v31" stroke="#f5c76e" stroke-width="2"/>')
        elements.append(
            f'<text x="{width - right + 10}" y="{y + 17}" fill="#f0f5fc" font-size="14">{fmt(group["median_hz"])} Hz'
            f'<tspan fill="#9eb2ce" font-size="11"> {group["valid"]}/{group["attempted"]} valid</tspan></text>'
        )
    elements.append("</svg>")
    return "".join(elements)


def summarize_directory(path):
    """Summaries for every run manifest directly under path; evidence paths stay relative."""
    path = Path(path).resolve()
    folders = (
        [path]
        if (path / "run.json").exists()
        else sorted(p.parent for p in path.glob("*/run.json"))
    )
    rows = [summarize_run(folder) for folder in folders]
    for row, folder in zip(rows, folders, strict=True):
        row["path"] = str(folder.relative_to(path))
    return path, folders, rows


def load_diagnostics(path):
    """Read diagnostics.json references; each entry is summarized separately, never pooled."""
    manifest_path = path / "diagnostics.json"
    result = dict(manifest_present=manifest_path.exists(), error=None, entries={})
    if not manifest_path.exists():
        return result
    try:
        manifest = json.loads(manifest_path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        result["error"] = f"diagnostics.json is unreadable: {exc}"
        return result
    if not isinstance(manifest, dict):
        result["error"] = "diagnostics.json must contain a JSON object"
        return result
    for key, reference in manifest.items():
        # "stability:first-attempt" keeps several attempts of one kind as separate sections.
        kind, _, label = str(key).partition(":")
        note = None
        if isinstance(reference, dict):
            # {"path": "../replay", "note": "why this attempt must be read with care"}
            note = reference.get("note")
            reference = reference.get("path")
        entry = dict(
            kind=kind,
            label=label or None,
            reference=reference,
            note=note if isinstance(note, str) and note.strip() else None,
            status="unavailable",
            error=None,
            link=None,
            runs=[],
            comparisons=[],
            campaign=None,
            probe=None,
        )
        result["entries"][str(key)] = entry
        if kind not in DIAGNOSTIC_KINDS:
            entry["error"] = (
                "unknown diagnostic kind; expected replay, stability, source_probe, "
                "replacement or extension"
            )
            continue
        if not isinstance(reference, str) or not reference.strip():
            entry["error"] = "reference must be a relative directory path"
            continue
        target = (path / reference).resolve()
        entry["link"] = os.path.relpath(target, path)
        if not target.is_dir():
            entry["error"] = f"referenced directory does not exist: {reference}"
            continue
        campaign = read_campaign(target)
        entry["campaign"] = {k: v for k, v in campaign.items() if not k.endswith("_moment")}
        if kind == "source_probe":
            summary_path = target / "summary.json"
            try:
                probe = json.loads(summary_path.read_text())
            except (OSError, json.JSONDecodeError) as exc:
                entry["error"] = f"probe summary unavailable: {exc}"
                continue
            if not isinstance(probe, dict) or not isinstance(probe.get("runs"), list):
                entry["error"] = "probe summary.json has no runs"
                continue
            entry["probe"] = dict(
                runs=[
                    {
                        key: run.get(key)
                        for key in (
                            "scenario",
                            "backend",
                            "repetition",
                            "status",
                            "target_hz",
                            "source_hz",
                            "received_hz",
                            "target_met",
                            "gap_percent",
                            "source_generation_p95_ms",
                            "source_deadline_misses",
                            "receive_age_p95_ms",
                            "throughput_mib_s",
                            "path",
                            "error",
                        )
                    }
                    for run in probe["runs"]
                    if isinstance(run, dict)
                ],
                report_present=(target / "report.html").exists(),
            )
            entry["status"] = "available"
            continue
        folders = []
        for manifest_file in sorted(target.glob("*/run.json")):
            try:
                record = json.loads(manifest_file.read_text())
            except (OSError, json.JSONDecodeError):
                continue
            if isinstance(record, dict) and "frontend" in record:
                folders.append(manifest_file.parent)
        if not folders:
            entry["error"] = f"no frontend run manifests under {reference}"
            continue
        for folder in folders:
            row = summarize_run(folder)
            row["path"] = os.path.relpath(folder, path)
            row["diagnostic"] = kind
            if kind == "stability":
                row["series"] = run_time_series(folder)
            entry["runs"].append(row)
        entry["comparisons"] = aggregate(entry["runs"])
        entry["status"] = "available"
    return result


def row_prefix(row):
    """Directory label for runs merged from an extension directory; empty for main runs."""
    return f"{row['extension']} · " if row.get("extension") else ""


def run_row_html(row, label_prefix=""):
    label = f"{escape(row['scenario'])}<small>{escape(row['mode'])} · repeat {row['repetition']}</small>"
    contract = row["metadata"].get("render_contract", "legacy fixed-window")
    label += f"<small>{escape(str(contract))}</small>"
    areas = row["metadata"].get("plot_viewports", {})
    label += f'<small>1D: {area_label(areas.get("waveform"))}<br>2D: {area_label(areas.get("image"))}</small>'
    anchor = report_anchor("run", row["path"], row["run_id"], label_prefix)
    run_id = f'<a href="#{anchor}">{escape(label_prefix)}{escape(row["run_id"])}</a>'
    return (
        f"<tr><td>{escape(row['frontend'])}<small>{run_id}</small></td><td>{escape(row['backend'])}</td>"
        f"<td>{label}</td><td>{escape(row['status'])}</td><td>{fmt(row['submitted_hz'])}</td>"
        f"<td>{fmt(row['source_hz'])}</td><td>{fmt(row['delivery_ack_hz'])}</td>"
        f"<td>{fmt(row['source_deadline_misses'], 0)}</td>"
        f"<td>{fmt(row['source_shortfall_percent'], 1)}</td><td>{fmt(row['delivery_drop_percent'], 1)}</td>"
        f"<td>{fmt(row['gap_percent'])}</td>"
        f"<td>{fmt(row['cpu_mean_percent'], 1)}</td><td>{fmt(row['rss_peak_mib'], 1)}</td></tr>"
    )


def run_details_html(row, label_prefix=""):
    record = dict(
        backend=row["backend"],
        config=row["config"],
        metadata=row["metadata"],
        error=row["error"],
        source_hz=row["source_hz"],
        source_generation_p95_ms=row["source_generation_p95_ms"],
        source_mailbox_drops=row["source_mailbox_drops"],
        source_deadline_misses=row["source_deadline_misses"],
        source_shortfall_percent=row["source_shortfall_percent"],
        delivery_drop_percent=row["delivery_drop_percent"],
        delivery_ack_hz=row["delivery_ack_hz"],
        provenance=row["provenance"],
        observed_display_contexts=row["observed_display_contexts"],
    )
    path = escape(row["path"])
    anchor = report_anchor("run", row["path"], row["run_id"], label_prefix)
    return (
        f'<details id="{anchor}"><summary>{escape(label_prefix)}{escape(row["run_id"])} · {escape(row["frontend"])} · {escape(row["mode"])} · {escape(row["backend"])} · {escape(row["scenario"])}</summary>'
        f"<pre>{escape(json.dumps(record, indent=2))}</pre>"
        f'<a href="{path}/measurements.jsonl">Raw measurements</a> · <a href="{path}/resources.jsonl">Resource samples</a> · '
        f'<a href="{path}/source.jsonl">Source samples</a> · <a href="{path}/frontend.log">Frontend log</a> · '
        f'<a href="{path}/host.json">Host metadata</a> · <a href="{path}/run.json">Run manifest</a></details>'
    )


RUN_TABLE_HEAD = (
    "<thead><tr><th>Frontend</th><th>Backend</th><th>Scenario</th><th>Status</th><th>Updates/s</th>"
    "<th>Source Hz</th><th>Delivery ACK Hz</th><th>Observed source misses</th>"
    "<th>Source shortfall %</th><th>Delivery drop %</th><th>Gaps %</th>"
    "<th>CPU %</th><th>RSS MiB</th></tr></thead>"
)


def comparison_sections_html(grouped, heading_level="h2", *, scope="main", compact=False):
    sections = []
    comparisons = defaultdict(list)
    for group in grouped:
        comparisons[group["scenario"], group["mode"], group["backend"]].append(group)
    for (scenario, mode, backend), groups in comparisons.items():
        anchor = report_anchor("comparison", scope, scenario, mode, backend)
        limited = any(group["source_limited"] for group in groups)
        note = (
            "The producer fell below target in at least one valid run; read source and delivery evidence before attributing the rate to the frontend."
            if limited
            else "Compare rates against the gold target marker. White ranges show the observed minimum and maximum across repetitions."
        )
        evidence = (
            f'<p><a href="report-extended.html#{anchor}">Open this comparison in the extended report</a></p>'
            if compact
            else (
                '<p><a href="#runs">Per-run measurements</a> · <a href="#evidence">Source/build evidence</a></p>'
                if scope == "main"
                else f'<p><a href="#{scope}">Diagnostic measurements and evidence</a></p>'
            )
        )
        sections.append(
            f'<section class="chart" id="{anchor}" data-scenario="{escape(scenario, quote=True)}" '
            f'data-mode="{escape(mode, quote=True)}" data-backend="{escape(backend, quote=True)}">'
            f"<{heading_level}>{escape(scenario)} <span>{escape(mode)} · {escape(backend)} source</span></{heading_level}>"
            f"<p>{note} Bars show median submitted update rates over valid repetitions, not displayed FPS.</p>"
            f'<div class="chart-scroll">{throughput_svg(groups)}</div>{evidence}</section>'
        )
    return "".join(sections)


def timing_sections_html(rows):
    sections = []
    for frontend in sorted({row["frontend"] for row in rows}):
        stage_rows = []
        for row in rows:
            if row["frontend"] != frontend:
                continue
            for stage, label in TIMING_STAGES.items():
                # Show absent observations too; never silently interpret them as zero time.
                if stage not in ("update", "draw") and not row[f"{stage}_samples"]:
                    continue
                stage_rows.append(
                    f'<tr><td>{escape(row_prefix(row))}{escape(row["run_id"])}<small>{escape(row["scenario"])} · {escape(row["mode"])} · {escape(row["backend"])}</small></td>'
                    f'<td>{escape(label)}</td><td>{row[f"{stage}_samples"]}/{row["samples"]} ({fmt(row[f"{stage}_coverage_percent"], 1)}%)</td>'
                    f'<td>{fmt(row[f"{stage}_p50_ms"])}</td><td>{fmt(row[f"{stage}_p95_ms"])}</td><td>{fmt(row[f"{stage}_p99_ms"])}</td></tr>'
                )
        boundaries = sorted(
            {
                str(row["metadata"].get("measurement_stage", "Not recorded"))
                for row in rows
                if row["frontend"] == frontend
            }
        )
        sections.append(
            f'<section id="{report_anchor("timing", frontend)}"><h2>{escape(frontend)} · timing stages</h2><p>{escape("; ".join(boundaries))}</p>'
            "<p>Stage observations are not additive and are not comparable to another adapter’s full-frame time. Coverage describes available telemetry, not screen presentation. Missing timings are shown as —.</p>"
            '<div class="scroll"><table><thead><tr><th>Run</th><th>Stage</th><th>Observation coverage</th><th>p50 ms</th><th>p95 ms</th><th>p99 ms</th></tr></thead>'
            f'<tbody>{"".join(stage_rows)}</tbody></table></div></section>'
        )
    return "".join(sections)


def hardware_html(hardware):
    if not hardware:
        return f"<p>Hardware: {NOT_RECORDED}. No campaign host snapshot or source host.json is available.</p>"
    memory = hardware.get("memory_gib")
    displays = []
    for display in hardware.get("displays") or []:
        flags = []
        if display.get("main"):
            flags.append("main display")
        if display.get("mirror") and display["mirror"] != "spdisplays_off":
            flags.append(f"mirror: {text(display['mirror'])}")
        displays.append(
            f"<li><strong>{text(display.get('name'))}</strong>{' (' + ', '.join(flags) + ')' if flags else ''}: "
            f"pixels {text(display.get('pixels'))}; configured {text(display.get('configured'))}; "
            f"scaling {text(display.get('scaling'))}; refresh field {text(display.get('refresh'))}; "
            f"{text(display.get('connection'))}; {text(display.get('kind'))}</li>"
        )
    graphics = [
        f"<li>{text(gpu.get('model'))} · vendor {text(gpu.get('vendor'))} · cores {text(gpu.get('cores'))} · Metal {text(gpu.get('metal'))}</li>"
        for gpu in hardware.get("graphics") or []
    ]
    rows = [
        ("Machine model", text(hardware.get("model_identifier"))),
        ("CPU", text(hardware.get("cpu_model"))),
        (
            "Physical / logical CPUs",
            f"{text(hardware.get('physical_cpus'))} / {text(hardware.get('logical_cpus'))}",
        ),
        ("Memory", NOT_RECORDED if memory is None else f"{memory:.1f} GiB"),
        ("Architecture", text(hardware.get("architecture"))),
        ("Operating system", text(hardware.get("os"))),
        ("Platform string", text(hardware.get("platform"))),
        ("GPU", f"<ul>{''.join(graphics)}</ul>" if graphics else NOT_RECORDED),
        ("Displays at capture", f"<ul>{''.join(displays)}</ul>" if displays else NOT_RECORDED),
        ("Recorded", f"{text(hardware.get('recorded_at'))} · {text(hardware.get('origin'))}"),
    ]
    if hardware.get("display_metadata_error"):
        rows.append(("Display query error", text(hardware["display_metadata_error"])))
    return (
        '<table class="facts"><tbody>'
        + "".join(f"<tr><th>{escape(name)}</th><td>{value}</td></tr>" for name, value in rows)
        + "</tbody></table>"
    )


def campaign_html(campaign, hardware, rows, missing, generated_at, extensions=()):
    extension_rows = [row for row in rows if row.get("extension")]
    rows = [row for row in rows if not row.get("extension")]
    recorded = len(rows)
    planned = campaign.get("runs_planned")
    valid = sum(row["status"] == "ok" for row in rows)
    limited = sum(bool(row.get("source_limited")) for row in rows)
    status = campaign["completion_status"]
    incomplete = (
        status in ("running", "interrupted", "error")
        or (planned is not None and recorded < planned)
        or bool(missing)
    )
    banner = ""
    if not campaign["manifest_present"]:
        banner = '<p class="banner"><strong>No campaign manifest.</strong> Acquisition dates, planned matrix and hardware snapshot were not recorded with these runs; values below come from run evidence where available.</p>'
    elif incomplete:
        reasons = [f"recorded status: {text(status)}"]
        if planned is not None:
            reasons.append(f"{recorded} of {planned} planned runs recorded")
        if missing:
            reasons.append(f"{len(missing)} planned runs absent")
        absent = ""
        if missing:
            absent = (
                "<details><summary>Absent planned runs</summary><ul>"
                + "".join(
                    f"<li>{text(job.get('scenario'))} · {text(job.get('mode'))} · {text(job.get('frontend'))} · {text(job.get('backend'))} · repeat {text(job.get('repetition'))}</li>"
                    for job in missing
                )
                + "</ul></details>"
            )
        banner = (
            f'<p class="banner"><strong>Incomplete campaign.</strong> {"; ".join(reasons)}. '
            f"Absent runs are listed and are not silently omitted.</p>{absent}"
        )
    elif status == "completed":
        banner = f'<p class="banner ok"><strong>Complete campaign.</strong> All {recorded} planned runs have a recorded manifest.</p>'
    else:
        banner = f'<p class="banner"><strong>Completion status not recorded</strong> (legacy manifest). All {recorded} planned runs have a recorded manifest; the acquisition end time is unknown.</p>'
    timing = " / ".join(
        text(campaign.get(key))
        for key in ("warmup_seconds", "measurement_seconds", "cooldown_seconds")
    )
    facts = [
        ("Acquisition start", text(campaign["started_at"])),
        ("Acquisition end", text(campaign["completed_at"])),
        ("Timezone of acquisition", text(campaign["timezone"])),
        ("Completion status", text(status)),
        ("Report generated", escape(describe_moment(generated_at))),
        ("Source backend(s)", text(campaign.get("backends"))),
        ("Frontend variants", text(campaign.get("frontends"))),
        ("Delivery modes", text(campaign.get("modes"))),
        ("Repetitions", text(campaign.get("repetitions"))),
        ("Warmup / measured / cooldown seconds", timing),
        ("Planned runs", text(planned)),
        ("Recorded runs", str(recorded)),
        ("Valid runs", str(valid)),
        ("Failed, excluded or incomplete runs", str(recorded - valid)),
        ("Runs with a generated-source shortfall", str(limited)),
        (
            "Extension runs merged into the comparison",
            (
                (
                    "; ".join(
                        f"{item['merged']} from {escape(item['label'])} ({', '.join(escape(f) for f in item['frontends'])}; "
                        f"acquired {text(item['started_at'])} to {text(item['completed_at'])}; {item['excluded']} excluded)"
                        for item in extensions
                    )
                    + f" · {len(extension_rows)} runs, {sum(row['status'] == 'ok' for row in extension_rows)} valid, counted separately from the {recorded} main runs"
                )
                if extensions
                else "none"
            ),
        ),
        ("Declared display context", text(campaign.get("display_context"))),
        ("Headless browser", text(campaign.get("headless"))),
        (
            "Command line",
            text(
                " ".join(campaign["argv"])
                if isinstance(campaign.get("argv"), list)
                else campaign.get("argv")
            ),
        ),
    ]
    if campaign.get("manifest_error"):
        facts.append(("Manifest error", text(campaign["manifest_error"])))
    facts_html = "".join(
        f"<tr><th>{escape(name)}</th><td>{value}</td></tr>" for name, value in facts
    )
    scenarios = campaign.get("cases")
    if scenarios:
        matrix_rows = []
        for case in scenarios:
            subset = [row for row in rows if row["scenario"] == case["name"]]
            worst_shortfall = max(
                (row.get("source_shortfall_percent") or 0 for row in subset), default=0.0
            )
            matrix_rows.append(
                f"<tr><td>{escape(case['name'])}</td><td>{escape(workload_label(case.get('config')))}</td>"
                f"<td>{len(subset)}</td><td>{sum(r['status'] == 'ok' for r in subset)}</td>"
                f"<td>{sum(bool(r.get('source_limited')) for r in subset)}</td>"
                f"<td>{fmt(worst_shortfall, 1)}</td></tr>"
            )
        matrix = (
            f"<h3>Scenario matrix ({len(scenarios)} scenarios)</h3>"
            '<div class="scroll"><table><thead><tr><th>Scenario</th><th>Workload</th><th>Recorded runs</th><th>Valid runs</th><th>Source-limited runs</th><th>Worst source shortfall %</th></tr></thead>'
            f'<tbody>{"".join(matrix_rows)}</tbody></table></div>'
        )
    else:
        matrix = f"<p>Scenario matrix: {NOT_RECORDED}.</p>"
    return (
        '<section id="campaign"><h2>Campaign</h2>'
        f"{banner}"
        f'<table class="facts"><tbody>{facts_html}</tbody></table>'
        f"{matrix}"
        "<h3>Hardware and display at acquisition</h3>"
        "<p>Values are the recorded acquisition-time snapshot; regenerating this report does not replace them with the report machine. The configured refresh rate is a display setting, not a measured presentation rate.</p>"
        f"{hardware_html(hardware)}</section>"
    )


def probe_table_html(probe, link):
    body = []
    for run in probe["runs"]:
        met = run.get("target_met")
        target_label = "—" if met is None else "Yes" if met else "No"
        evidence = (
            f'<a href="{escape(link)}/{escape(run["path"])}/run.json">Details</a>'
            if run.get("path")
            else "—"
        )
        body.append(
            f'<tr><td>{text(run.get("scenario"))}</td><td>{text(run.get("backend"))}</td><td>{text(run.get("repetition"))}</td>'
            f'<td>{text(run.get("status"))}</td><td>{fmt(run.get("target_hz"))}</td><td>{fmt(run.get("source_hz"))}</td>'
            f'<td>{fmt(run.get("received_hz"))}</td><td>{fmt(run.get("gap_percent"))}</td><td>{fmt(run.get("source_generation_p95_ms"))}</td>'
            f"<td>{target_label}</td><td>{evidence}</td></tr>"
        )
    return (
        '<div class="scroll"><table><thead><tr><th>Workload</th><th>Backend</th><th>Repeat</th><th>Status</th><th>Target Hz</th>'
        "<th>Source Hz</th><th>Received Hz</th><th>Gaps %</th><th>Generation p95 ms</th><th>Target met</th><th>Evidence</th></tr></thead>"
        f'<tbody>{"".join(body)}</tbody></table></div>'
    )


def diagnostics_html(diagnostics, main_count):
    sections = []
    if not diagnostics["manifest_present"]:
        sections.append(
            '<section id="diagnostics"><h2>Follow-up diagnostics</h2><p>No <code>diagnostics.json</code> manifest is present beside these runs. Replay, stability and source-probe diagnostics were not run or were not linked.</p></section>'
        )
        return "".join(sections)
    if diagnostics["error"]:
        sections.append(
            f'<section id="diagnostics"><h2>Follow-up diagnostics</h2><p class="banner">{escape(diagnostics["error"])}</p></section>'
        )
    for kind, (base_title, description) in DIAGNOSTIC_KINDS.items():
        entries = [e for e in diagnostics["entries"].values() if e["kind"] == kind]
        if not entries:
            sections.append(
                f'<section class="diagnostic"><h2>{escape(base_title)}</h2><p>Not run or not linked: <code>diagnostics.json</code> has no <code>{escape(kind)}</code> entry.</p></section>'
            )
            continue
        for entry in entries:
            title = base_title + (f" · {entry['label']}" if entry.get("label") else "")
            sections.append(diagnostic_entry_html(kind, title, description, entry, main_count))
    for entry in diagnostics["entries"].values():
        if entry["kind"] not in DIAGNOSTIC_KINDS:
            sections.append(
                f'<section class="diagnostic" id="{diagnostic_anchor(entry)}"><h2>{escape(str(entry["kind"]))}</h2><p class="banner">Unavailable: {escape(str(entry["error"]))} (reference {text(entry["reference"])}).</p></section>'
            )
    return "".join(sections)


def diagnostic_entry_html(kind, title, description, entry, main_count):
    anchor = diagnostic_anchor(entry)
    if entry["status"] != "available":
        return f'<section class="diagnostic" id="{anchor}"><h2>{escape(title)}</h2><p class="banner">Unavailable: {escape(str(entry["error"]))} (reference {text(entry["reference"])}).</p></section>'
    campaign = entry["campaign"] or {}
    note = (
        f'<p class="banner"><strong>Operator note.</strong> {escape(entry["note"])}</p>'
        if entry.get("note")
        else ""
    )
    header = (
        f"<p>{escape(description)}</p>{note}"
        f"<p>Evidence directory <code>{escape(entry['link'])}</code>, separate from the {main_count} main comparison runs. "
        f"Acquisition {text(campaign.get('started_at'))} to {text(campaign.get('completed_at'))}, timezone {text(campaign.get('timezone'))}, "
        f"status {text(campaign.get('completion_status'))}. Warmup / measured / cooldown seconds: "
        f"{text(campaign.get('warmup_seconds'))} / {text(campaign.get('measurement_seconds'))} / {text(campaign.get('cooldown_seconds'))}; "
        f"repetitions {text(campaign.get('repetitions'))}; frontends {text(campaign.get('frontends'))}; modes {text(campaign.get('modes'))}; backends {text(campaign.get('backends'))}.</p>"
    )
    if kind == "source_probe":
        link = (
            f'<p><a href="{escape(entry["link"])}/report.html">Open the probe report</a> · <a href="{escape(entry["link"])}/summary.json">Probe summary JSON</a></p>'
            if entry["probe"]["report_present"]
            else ""
        )
        return (
            f'<section class="diagnostic" id="{anchor}"><h2>{escape(title)}</h2>{header}{link}'
            f"<p>{len(entry['probe']['runs'])} receiver-only runs. Target met requires both generation and decoded receipt to reach 98% of the requested rate in that repetition.</p>"
            f'{probe_table_html(entry["probe"], entry["link"])}</section>'
        )
    rows = entry["runs"]
    valid = sum(row["status"] == "ok" for row in rows)
    if kind == "extension":
        merged = entry.get("merged_run_ids") or []
        excluded = entry.get("excluded_runs") or []
        excluded_html = (
            "<ul>"
            + "".join(
                f"<li>{escape(item['run_id'])} · {escape(item['frontend'])} · {escape(item['scenario'])}: {escape('; '.join(item['reasons']))}</li>"
                for item in excluded
            )
            + "</ul>"
            if excluded
            else "<p>No runs were excluded.</p>"
        )
        return (
            f'<section class="diagnostic" id="{anchor}"><h2>{escape(title)}</h2>{header}'
            f"<p>{len(rows)} runs recorded in <code>{escape(entry['link'])}</code>; {valid} valid; {len(merged)} merged into the comparison above under the "
            f"<code>{escape(entry.get('label') or kind)}</code> label; {len(excluded)} excluded. Merged runs appear in the charts, the per-run table, the timing tables and the CSV/JSON with their label; they never share a bar with the original runs.</p>"
            f'<p><a href="{escape(entry["link"])}/report.html">Open the extension directory\'s own report</a> · <a href="{escape(entry["link"])}/summary.json">Its summary JSON</a></p>'
            f"<h3>Excluded runs</h3>{excluded_html}</section>"
        )
    prefix = f"{kind}{' · ' + entry['label'] if entry.get('label') else ''} · "
    body = f"<p>{len(rows)} runs recorded in this diagnostic; {valid} valid. Run identifiers repeat across result directories, so they are shown with the <code>{escape(prefix.strip(' ·'))}</code> prefix and link to their own directory.</p>"
    if kind == "stability":
        charts = []
        for row in rows:
            series = row.get("series")
            if series is None:
                charts.append(
                    f'<h3>{escape(row["frontend"])} · {escape(row["scenario"])} · {escape(row["run_id"])}</h3><p>No submitted samples were recorded; no time series is available.</p>'
                )
                continue
            caption = (
                f"Measured window {series['measurement_seconds']:g} s after a {series['warmup_seconds']:g} s warmup; "
                f"{series['zero_bins']} of {len(series['submissions_per_bin'])} one-second bins had no submission; "
                f"{series['resource_observations']} RSS observations. Status: {escape(row['status'])}. "
                "Submission throughput is not displayed FPS; a missing RSS observation is shown as a gap, not as zero."
            )
            charts.append(
                f'<h3>{escape(row["frontend"])} · {escape(row["scenario"])} · {escape(row["run_id"])}</h3>'
                f'{series_svg(series, title=f"{row["frontend"]} submissions and RSS over time")}<p>{caption}</p>'
            )
        body += "".join(charts)
    else:
        body += comparison_sections_html(entry["comparisons"], heading_level="h3", scope=anchor)
    body += (
        f'<div class="scroll"><table>{RUN_TABLE_HEAD}<tbody>{"".join(run_row_html(row, prefix) for row in rows)}</tbody></table></div>'
        + "".join(run_details_html(row, prefix) for row in rows)
    )
    return f'<section class="diagnostic" id="{anchor}"><h2>{escape(title)}</h2>{header}{body}</section>'


def merge_extensions(campaign, diagnostics):
    """Extension runs that match the main suite exactly; mismatches stay listed and excluded."""
    from .config import Config

    def normalized(config):
        """Full configuration with defaults, without the server-assigned generation."""
        fields = {k: v for k, v in (config or {}).items() if k != "generation"}
        try:
            fields = Config(**fields).to_dict()
        except (TypeError, ValueError):
            return fields
        return {k: v for k, v in fields.items() if k != "generation"}

    cases = {}
    for case in campaign.get("cases") or []:
        try:
            cases[case["name"]] = normalized(case["config"])
        except (KeyError, TypeError):
            continue
    modes, backends = campaign.get("modes") or [], campaign.get("backends") or []
    merged = []
    for key, entry in diagnostics["entries"].items():
        if entry["kind"] != "extension":
            continue
        entry["merged_run_ids"], entry["excluded_runs"] = [], []
        if entry["status"] != "available":
            continue
        label = entry.get("label") or key
        for row in entry["runs"]:
            reasons = []
            if not cases:
                reasons.append("the main campaign has no manifest to validate against")
            elif row["scenario"] not in cases:
                reasons.append("scenario is not in the main suite")
            elif cases[row["scenario"]] != normalized(row["config"]):
                reasons.append("workload configuration differs from the main suite")
            if modes and row["mode"] not in modes:
                reasons.append("delivery mode is not part of the main suite")
            if backends and row["backend"] not in backends:
                reasons.append("source backend is not part of the main suite")
            for key_name, label_text in (
                ("measurement_seconds", "measured duration differs"),
                ("warmup_seconds", "warmup differs"),
            ):
                if campaign.get(key_name) is not None and row.get(key_name) != campaign[key_name]:
                    reasons.append(label_text)
            if reasons:
                entry["excluded_runs"].append(
                    dict(
                        run_id=row["run_id"],
                        scenario=row["scenario"],
                        frontend=row["frontend"],
                        reasons=reasons,
                    )
                )
                continue
            row["extension"] = label
            entry["merged_run_ids"].append(row["run_id"])
            merged.append(row)
    return merged


def build_report(path):
    """Write compact/extended offline HTML and shared summaries; return the compact path."""
    path, folders, rows = summarize_directory(path)
    if not folders:
        raise ValueError(f"no run manifests in {path}")
    generated_at = local_now()
    campaign = read_campaign(path)
    hardware = campaign.get("hardware") or legacy_hardware(folders)
    missing = missing_jobs(campaign.get("planned_jobs"), rows)
    diagnostics = load_diagnostics(path)
    extension_rows = merge_extensions(campaign, diagnostics)
    for row in rows:
        row.setdefault("extension", None)
    all_rows = rows + extension_rows
    grouped = aggregate(all_rows)
    extensions = [
        dict(
            label=entry.get("label") or key,
            link=entry["link"],
            merged=len(entry.get("merged_run_ids") or []),
            excluded=len(entry.get("excluded_runs") or []),
            frontends=sorted({row["frontend"] for row in entry["runs"]}),
            started_at=(entry.get("campaign") or {}).get("started_at"),
            completed_at=(entry.get("campaign") or {}).get("completed_at"),
        )
        for key, entry in diagnostics["entries"].items()
        if entry["kind"] == "extension" and entry["status"] == "available"
    ]
    campaign_record = {k: v for k, v in campaign.items() if not k.endswith("_moment")}
    campaign_record.update(
        hardware=hardware,
        missing_runs=missing,
        recorded_runs=len(rows),
        valid_runs=sum(row["status"] == "ok" for row in rows),
        extensions=extensions,
        merged_extension_runs=len(extension_rows),
        report_generated_at=generated_at.isoformat(),
    )
    rows = all_rows
    summary = dict(
        report_provenance=capture_provenance(),
        report_generated_at=generated_at.isoformat(),
        campaign=campaign_record,
        runs=rows,
        comparisons=grouped,
        diagnostics=diagnostics,
        definitions=dict(
            submitted_hz="measured submitted updates / fixed measured seconds",
            update_ms="frontend-specific synchronous update boundary; consult each adapter metadata",
            draw_ms="optional observed draw work; may overlap update_ms; missing is not zero",
            update_complete_ms="adapter preparation through its completion signal, including asynchronous wait; not displayed latency",
            image_upload_wait_ms="Iced allocation task through completion notification; includes scheduling, not pure GPU time",
            timing_coverage_percent="samples with a finite nonnegative stage observation / measured submissions; not displayed-frame coverage",
            gap_percent="missing sequence IDs / observed sequence span, excluding unobserved leading/trailing gaps",
            cpu_percent="sum across frontend process tree; 100% equals one logical CPU",
            source_hz="source frames produced during the frontend's measured interval",
            delivery_ack_hz="decoded-frame ACK counter increase / leading single-client source counter span inside the measured window (trailing samples after the client disconnected are excluded); unavailable with other client counts; not presentation and not exactly the full measurement window",
            completion_latency_seconds="browser runs: seconds from the nominal end of the run to the page's flushed completion signal; teardown work, not plotting or presentation",
            source_generation_p95_ms="p95 generation/packing/enqueue duration; consult backend implementation",
            source_mailbox_drops="produced frames replaced in the server mailbox while delivery awaited ACK",
            source_deadline_misses="increase in cumulative missed-deadline counter between first and last source sample in the measured window; boundary misses may be unobserved",
            source_shortfall_percent="stream only: how far the source generation rate fell below target, 100·(target − source Hz)/target, clamped at 0; the magnitude of source limiting, independent of the renderer",
            delivery_drop_percent="produced frames replaced in the mailbox awaiting ACK as a percentage of frames produced in the window; the magnitude of frontend/delivery limiting, where the renderer could not consume at the offered rate",
            submissions_per_bin="stability diagnostics: submitted samples per one-second bin after warmup, zero bins included; not displayed FPS",
            rss_mib="stability diagnostics: resident memory of the frontend process tree per resource observation inside the measured window; missing observations remain missing",
        ),
    )
    (path / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    columns = list(
        dict.fromkeys(
            key
            for row in rows
            for key in row
            if key
            not in ("metadata", "config", "provenance", "observed_display_contexts", "series")
        )
    )
    with (path / "summary.csv").open("w", newline="") as output:
        writer = csv.DictWriter(output, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    failures = [row for row in rows if row["status"] != "ok"]
    smoke = any(row["measurement_seconds"] < 30 for row in rows)
    classification = (
        "Smoke validation — use longer repeated runs before drawing performance conclusions."
        if smoke
        else "Repeated workload measurements — compare equivalent scenarios and inspect timing boundaries before selecting a renderer."
    )
    html = f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Plotting benchmark · Extended report</title>
<style>:root{{font:16px system-ui;color:#e9f0fa;background:#0e1420}}body{{max-width:1120px;margin:0 auto;padding:48px 24px}}h1{{font-size:44px;letter-spacing:-1.5px}}h2{{font-size:23px}}h3{{font-size:18px;margin-top:26px}}h2 span,h3 span{{font-size:13px;color:#65ddc2;padding-left:14px}}p,li{{color:#b3c2d6;line-height:1.65}}.tag{{color:#65ddc2;letter-spacing:2px;font-size:12px}}section{{margin:28px 0;padding:24px;background:#172235;border-radius:12px}}section.diagnostic{{border-left:4px solid #7aa6ff}}svg{{width:100%;max-height:none}}table{{width:100%;border-collapse:collapse;font-size:13px}}th,td{{text-align:left;padding:13px 10px;border-bottom:1px solid #314158;white-space:nowrap}}th{{color:#9eb2ce;font-weight:500}}table.facts th{{width:280px;vertical-align:top}}table.facts td{{white-space:normal;overflow-wrap:anywhere}}table.facts ul{{margin:0;padding-left:18px}}small{{display:block;color:#91a6c2;margin-top:5px}}.scroll{{overflow:auto}}a{{color:#65ddc2}}details{{border-top:1px solid #314158;padding:15px 0}}summary{{cursor:pointer}}pre{{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.5}}code{{color:#e9f0fa}}input{{background:#101a2b;color:white;border:1px solid #405577;border-radius:6px;padding:10px;width:280px}}.banner{{border-left:4px solid #f5c76e;padding:10px 14px;background:#22304a;border-radius:6px}}.banner.ok{{border-left-color:#63d7b9}}@media print{{:root{{color:#101820;background:white}}section{{background:#eef2f8}}p,li,small{{color:#334155}}details{{display:block}}}}</style>
</head><body><div class="tag">PLOTBENCH / RECORDED MEASUREMENTS</div><h1>Plotting benchmark report</h1><p>Extended view · {text(campaign.get('suite_name'))}</p>
<nav aria-label="Report navigation"><a href="report.html">Compact report</a> · <a href="#campaign">Campaign</a> · <a href="#comparisons">Charts</a> · <a href="#runs">Runs</a> · <a href="#timings">Timing stages</a> · <a href="#followup-evidence">Diagnostics</a> · <a href="#evidence">Evidence</a></nav>
{campaign_html(campaign, hardware, rows, missing, generated_at, extensions)}
<section><h2>Technical summary</h2><p>{classification}</p><p>{len(rows)} runs recorded; {len(failures)} failed or lacked usable data. Every result retains its configuration, raw samples and adapter measurement boundary. No displayed-FPS or GPU-time ranking is inferred.</p></section>
<section id="methodology"><h2>Read the measurements consistently</h2><p>Submitted updates/s counts measured updates over a fixed interval after warmup. A submitted update does not prove screen presentation. Update-duration percentiles describe each adapter’s documented synchronous work: Matplotlib includes Agg rasterization, while GPU frontends can return before GPU completion. Compare end-to-end throughput within a workload; do not interpret these API durations as equivalent GPU timings.</p><p>Source Hz counts generated frames. Delivery ACK Hz estimates decoded delivery from source-observed acknowledgements for a single client over the available counter span. Missing counters or multiple clients produce —, not zero. It is not a plotted or presented frame rate. Backend identity is recorded and comparisons keep Python and Rust separate. Streaming includes transport and conversion; replay cycles a bounded CPU-resident dataset generated by the same source. Sequence gaps include skipped source deadlines and coalesced updates. Gap percentages cover the observed sequence span; throughput also exposes startup or tail starvation. Approximate receive age uses same-host wall clocks and is not presentation latency.</p><p><strong>Check the rendering contract.</strong> Runs marked data-area-v1 or data-area-v2 normalize data rectangles, preserve image aspect ratio and validate every measured plot against a common target. Invalid geometry excludes a run. Unversioned legacy runs compare fixed windows whose data areas can differ. Device scale remains part of the comparison context. Native axes, text and renderer-specific edge treatment still differ; Plotly scattergl retains default antialiasing.</p><p>CPU is the frontend process-tree sum (100% = one logical CPU). RSS sums resident memory and can count shared pages more than once. Browser resources include the automation driver. GPU utilization and monitor presentation timing are not captured portably.</p></section>
<div id="comparisons">{comparison_sections_html(grouped)}</div>
<section><h2>Per-run measurements</h2><p>Percentiles are computed per repetition from raw samples. The comparison charts use the median repetition rate and observed range, without pooling different workloads, source backends, source/build identities or recorded display/runtime contexts. Multiple bars with a context suffix identify distinct execution conditions. Filter the table to inspect a frontend or scenario.</p><input id="filter" placeholder="Filter runs…" aria-label="Filter runs"><div class="scroll"><table id="runs">{RUN_TABLE_HEAD}<tbody>{"".join(run_row_html(row, row_prefix(row)) for row in rows)}</tbody></table></div></section>
<div id="timings">{timing_sections_html(rows)}</div>
<section><h2>Next measurements</h2><p>For a selection decision, run at least three 30-second measurements per target workload on an otherwise idle machine. Keep window pixel area, display scaling and refresh rate fixed. Inspect source-limited runs using replay, then validate visually and under interactive use. A 120 Hz input stream alone does not establish 120 visible frames/s. Consult each adapter's documentation for its implementation and maintenance requirements.</p></section>
<div id="followup-evidence">{diagnostics_html(diagnostics, len(rows))}</div>
<section id="evidence"><h2>Reproduce and audit</h2><p><a href="summary.csv">Download CSV</a> · <a href="summary.json">Download structured summary</a>. Source/build provenance is retained per run. The report generator’s separate provenance and generation time are in summary.json. Expand a run to inspect exact configuration and timing semantics.</p>{"".join(run_details_html(row, row_prefix(row)) for row in rows)}</section>
<script>document.querySelector('#filter').addEventListener('input',event=>{{const query=event.target.value.toLowerCase();for(const row of document.querySelectorAll('#runs tbody tr'))row.hidden=!row.textContent.toLowerCase().includes(query)}});function openEvidence(){{const target=document.getElementById(location.hash.slice(1));if(target&&target.tagName==='DETAILS'){{target.open=true;target.scrollIntoView();}}}}window.addEventListener('hashchange',openEvidence);openEvidence();</script></body></html>"""
    (path / "report-extended.html").write_text(html)
    target = path / "report.html"
    target.write_text(compact_report_html(summary, comparison_sections_html(grouped, compact=True)))
    return target
